### ISSUE TITLE
Ajenti repo is deprecated

### ISSUE THREAD

**Issue by tetri** [trananhkma/fucking-awesome-python#4]
According to [Ajenti repo](https://github.com/Eugeny/ajenti) link provided in fucking-awesome-python, [that repo](https://github.com/Eugeny/ajenti) is deprecated.

The new repo is [this](https://github.com/ajenti/ajenti). So star feature is deprecated too.

**Comment by trananhkma** [comment]
Thank you for poiting this out. It would be verry much appreciated.
I will update on next commit. 
Thanks
